# Generated by Django 4.2 on 2024-12-03 11:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyowner_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['title'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='location',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('continent', 'Continent'), ('country', 'Country'), ('state', 'State'), ('city', 'City')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='properties.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_abbr',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
